version: '2.2'
services:

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuserpassword
    restart: always
    ports:
      - 8002:3306
    healthcheck:
      test: "/etc/init.d/mysql status"
      timeout: 20s
      retries: 10
  app:
    image: servme-fad/lumen-base
    container_name: app
    restart: always
    volumes:
      - ./:/var/www
    entrypoint: ['/bin/bash', '/var/www/start.sh']
    ports:
      - 8001:80
    depends_on:
      db:
        condition: service_healthy
